/**
 * Mule Freshbooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.modules.freshbooks;

import org.junit.BeforeClass;
import org.junit.Test;
import org.mule.modules.freshbooks.model.Category;
import org.mule.modules.freshbooks.model.WCategory;

public class FreshbooksModuleTestDriver
{
    private static FreshbooksModule module;
    
    @BeforeClass
    public static void init()
    {
        module = new FreshbooksModule();
        module.setApiUrl("https://mulesofttest.freshbooks.com/api/2.1/xml-in");
        module.setAuthenticationToken("4d8a62a53ec1b3426a625abd039babd9");
        module.init();
    }
    @Test
    public void invokeSomeMethodOnTheCloudConnector()
    {
    /*
        Add code that tests the cloud connector at the API level. This means that you'll
        instantiate your cloud connector directly, invoke one of its methods and assert
        you get the correct result.

        Example:

        FreshbooksCloudConnector connector = new FreshbooksCloudConnector();
        Object result = connector.someMethod("sample input");
        assertEquals("expected output", result);
     */
    }
    @Test
    public void createACategoryAndDeleteIt()
    {
        Category cat =  new Category();
        cat.setName("MegaMarket3");
        WCategory wCategory = new WCategory();
        wCategory.setCategory(cat);
        
        String categoryId = module.createCategory(wCategory);
        cat.setId(categoryId);
        module.deleteCategory(wCategory);
    }
}
