/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.modules.freshbooks.config;

import org.mule.api.MuleEvent;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.tck.FunctionalTestCase;

public class FreshbooksNamespaceHandlerTestCase extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return"freshbooks-namespace-config.xml";
    }

    public void testCategoryFlow()throws Exception
    {
        String payload = null;
        SimpleFlowConstruct flow = lookupFlowConstruct("categoryFlow");
        MuleEvent event = getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);
        //assertEquals(<expected test output>, responseEvent.getMessage().getPayloadAsString());
        //String out = responseEvent.getMessage().getPayloadAsString();
    }

    public void testClientFlow()throws Exception
    {
        String payload = null;
        SimpleFlowConstruct flow = lookupFlowConstruct("clientFlow");
        MuleEvent event = getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);
        //assertEquals(<expected test output>, responseEvent.getMessage().getPayloadAsString());
        //String out = responseEvent.getMessage().getPayloadAsString();
    }

    private SimpleFlowConstruct lookupFlowConstruct(String name)
    {
        return(SimpleFlowConstruct)muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
